version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Bridge-tecnologia-e-consultoria/devops"
    auto-merge:
      auto-commit: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Bridge-tecnologia-e-consultoria/devops"
    auto-merge:
      auto-commit: true
